apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
     app: nginx-redis-memcached
spec:
  containers:
  - name: con1
    image: nginx:alpine
  - name: con2
    image: redis
  - name: con3
    image: memcached