apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-with-sidecar-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server-with-sidecar
  template:
    metadata:
      labels:
        app: app-server-with-sidecar
    spec:
      containers:
      - name: app-server-with-sidecar
        image: jxlwqq/http-echo:latest
        args:
        - "--text=hello-to-banana-xxx"
      - name: nginx-sidecar
        image: nginx:alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - name: nginx-conf-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf-vol
        configMap:
          name: nginx-conf
      - name: secret-volume
        secret:
          secretName: http-tls
---
apiVersion: v1
kind: Service
metadata:
  name: app-server-with-sidecar-svc
spec:
  selector:
    app: app-server-with-sidecar
  type: NodePort
  ports:
  - nodePort: 30010
    port: 443