apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
  labels:
     app: livess-pro
spec:
  containers:
  - name: echo-server
    image: registry.cloudyuga.guru/library/http-echo:0.2.3
    args: ["-listen", ":8080", "-text", "example for tcp liveness probe"]
    ports:
      - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1